annotations:
  artifacthub.io/alternativeName: Mage-Ingress
  artifacthub.io/category: networking
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Homepage
      url: https://www.mage.ai/
    - name: Source
      url: https://github.com/mage-ai/helm-charts
    - name: Documentation
      url: https://mage-ai.github.io/helm-charts/
  artifacthub.io/maintainers: |
    - name: Mage
      email: eng@mage.ai
  artifacthub.io/screenshots: |
    - title: Build Pipeline
      url: https://www.mage.ai/images/pages/home/screenshots/v5/Build@2x.png
    - title: Preview Pipeline
      url: https://www.mage.ai/images/pages/home/screenshots/v5/Preview@2x.png
    - title: Launch Pipeline
      url: https://www.mage.ai/images/pages/home/screenshots/v5/Launch@2x.webp

apiVersion: v2

description: A Helm chart for deploying ingress for Mage AI

home: https://www.mage.ai

icon: https://avatars.githubusercontent.com/u/69371472

maintainers:
  - name: mage-ai
    url: https://www.mage.ai
    email: eng@mage.ai

name: mageai-ingress


sources:
- https://github.com/mage-ai/helm-charts/tree/master/charts/ingress

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1
