apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mageai.fullname" . }}
  labels:
    {{- include "mageai.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mageai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mageai.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mageai.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{ if .Values.livenessProbe.enabled | default true -}}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path | default "/api/status" }}
              port: {{ .Values.livenessProbe.port | default "http" }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 5 }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            terminationGracePeriodSeconds: {{ .Values.livenessProbe.terminationGracePeriodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 1 }}
          {{- end }}
          {{ if .Values.readinessProbe.enabled | default true -}}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path | default "/api/status" }}
              port: {{ .Values.readinessProbe.port | default "http" }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 5 }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            terminationGracePeriodSeconds: {{ .Values.readinessProbe.terminationGracePeriodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
          {{- if .Values.extraVolumeMounts -}}
            {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- else if .Values.volumes }}
            - name: mage-fs
              mountPath: /home/src
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.extraVolumes -}}
        {{ toYaml .Values.extraVolumes | nindent 8 }}
      {{- else if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
