{{ if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mageai.fullname" . }}-secert-env
  labels:
    {{- include "mageai.labels" . | nindent 4 }}
stringData:
  {{ toYaml .Values.secrets | indent 2 }}
{{ end }}
